version: 2

updates:
  - package-ecosystem: 'npm'
    # this will ensure that dependabot will only scan the packages in the root directory
    # omitting the packages in the /examples directory
    directory: '/'
    schedule:
      interval: 'monthly'
